# Generated by Django 5.1.7 on 2025-04-02 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_nome_azienda_ragionesociale'),
        ('anagrafiche', '0002_dogana_created_at_dogana_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogana',
            name='azienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.azienda'),
        ),
        migrations.AddField(
            model_name='fornitore',
            name='azienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.azienda'),
        ),
    ]
