version: '3.9'
services:
  web:
    build: .
    command: /code/entrypoint.sh
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - '8000:8000'
    env_file: .env
    depends_on:
      - db
    environment:
      - DB_HOST=db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5434:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  db_backup:
    image: tiredofit/db-backup
    container_name: db_backup
    restart: always
    entrypoint: ['/bin/bash', '/custom-entrypoint.sh']
    user: '${BACKUP_UID}:${BACKUP_GID}'
    environment:
      - DB_TYPE=postgres
      - DB_HOST=${DB_HOST}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_PORT=${DB_PORT}
      - SCHEDULE=${BACKUP_SCHEDULE}
      - COMPRESSION=${BACKUP_COMPRESSION}
      - MD5=${BACKUP_MD5}
      - SPLIT_DB=${BACKUP_SPLIT_DB}
      - ENABLE_CHECKSUM=${BACKUP_ENABLE_CHECKSUM}
    volumes:
      - ${BACKUP_DIR}:/backup
      - ./entrypoint_backup.sh:/custom-entrypoint.sh:ro
    depends_on:
      - db
    profiles:
      - backup

volumes:
  postgres_data:
  static_volume:
  media_volume:
