version: '3.9'
services:
  web:
    build: .  
    command: /code/entrypoint.sh  
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data      
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # Configura PostgreSQL per accettare connessioni esterne
      POSTGRES_HOST_AUTH_METHOD: "md5"  # Usa autenticazione con password
    command: >
      postgres
        -c listen_addresses='*'  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 3s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/code/staticfiles
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
  

volumes:
  postgres_data:
  static_volume:
  
