# Generated by Django 5.1.7 on 2025-03-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_azienda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='azienda',
            old_name='nome',
            new_name='ragionesociale',
        ),
    ]
