# Generated by Django 4.2.20 on 2025-04-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_azienda_cf_rappresentante_azienda_codice_carica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='gender_rappresentante',
            field=models.CharField(choices=[('M', 'Maschio'), ('F', 'Femmina')], default='M', max_length=1, verbose_name='Sesso'),
        ),
    ]
