# Generated by Django 4.2.20 on 2025-04-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_azienda_gender_rappresentante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azienda',
            name='comune_nascita',
        ),
        migrations.AddField(
            model_name='azienda',
            name='comune_nascita_rappresentante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='azienda',
            name='provincia_nascita_rappresentante',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='provincia',
            field=models.CharField(max_length=100),
        ),
    ]
