# Generated by Django 4.2.25 on 2025-10-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_azienda_comune_nascita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azienda',
            name='codice_carica',
            field=models.CharField(blank=True, choices=[('1', 'Rappresentante legale, negoziale o di fatto, socio amministratore'), ('2', "Rappresentante di minore, inabilitato o interdetto, amministratore di sostegno, ovvero curatore dell'eredità giacente, amministratore di eredità devoluta sotto condizione sospensiva o in favore di nascituro non ancora concepito"), ('3', 'Curatore fallimentare'), ('4', 'Commissario liquidatore (liquidazione coatta amministrativa ovvero amministrazione straordinaria)'), ('5', 'Custode giudiziario (custodia giudiziaria), ovvero amministratore giudiziario in qualità di rappresentante dei beni sequestrati ovvero commissario giudiziale (amministrazione controllata)'), ('6', 'Rappresentante fiscale di soggetto non residente'), ('7', 'Erede'), ('8', 'Liquidatore (liquidazione volontaria)'), ('9', "Soggetto tenuto a presentare la comunicazione ai fini IVA per conto del soggetto estinto a seguito di operazioni straordinarie o altre trasformazioni sostanziali soggettive (cessionario d'azienda, società beneficiaria, incorporante, conferitaria, ecc.)la comunicazione."), ('10', "Rappresentante fiscale di soggetto non residente con le limitazioni di cui all'art. 44, comma 3, del D.L. n. 331/1993"), ('11', "Soggetto esercente l'attività tutoria del minore o interdetto in relazione alla funzione istituzionale rivestita"), ('12', 'Liquidatore (liquidazione volontaria di ditta individuale - periodo ante messa in liquidazione)'), ('13', 'Amministratore di condominio'), ('14', 'Soggetto che sottoscrive la dichiarazione per conto di una pubblica amministrazione'), ('15', 'Commissario liquidatore di una pubblica amministrazione')], verbose_name='Codice Carica'),
        ),
    ]
