# Generated by Django 5.1.7 on 2025-03-27 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0003_dogana_alter_fornitore_citta'),
        ('documenti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dichiarazioneintento',
            name='fk_dogana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anagrafiche.dogana', verbose_name='Dogana'),
        ),
        migrations.AddField(
            model_name='dichiarazioneintento',
            name='importosingolo',
            field=models.BooleanField(default=False, verbose_name='Importo Singolo'),
        ),
        migrations.AddField(
            model_name='dichiarazioneintento',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='dichiarazioneintento',
            name='tipo_operazione',
            field=models.CharField(blank=True, choices=[('A', 'Acquisto'), ('I', 'Importazione')], max_length=1, verbose_name='Tipo Operazione'),
        ),
    ]
