# Generated by Django 5.1.7 on 2025-04-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documenti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fatturafornitore',
            options={'ordering': ['-data_fattura']},
        ),
    ]
