# Generated by Django 4.2.20 on 2025-04-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documenti', '0004_fatturafornitore_azienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dichiarazioneintento',
            name='tipo_operazione',
            field=models.CharField(choices=[('A', 'Acquisto'), ('I', 'Importazione')], max_length=1, verbose_name='Tipo Operazione'),
        ),
    ]
