# Generated by Django 4.2.20 on 2025-04-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documenti', '0005_alter_dichiarazioneintento_tipo_operazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='dichiarazioneintento',
            name='plafond_singolo',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=12),
            preserve_default=False,
        ),
    ]
