# Generated by Django 4.2.20 on 2025-04-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documenti', '0006_dichiarazioneintento_plafond_singolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dichiarazioneintento',
            name='plafond',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='dichiarazioneintento',
            name='plafond_singolo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
