# Generated by Django 4.2.20 on 2025-04-14 13:27

from django.db import migrations, models
import documenti.models


class Migration(migrations.Migration):

    dependencies = [
        ('documenti', '0008_durc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='durc',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to=documenti.models.durc_upload_path),
        ),
    ]
