# Generated by Django 4.2.20 on 2025-05-06 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documenti', '0011_alter_dichiarazioneintento_numero_dichiarazione'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dichiarazioneintento',
            options={'ordering': ['-data_dichiarazione', '-numero_interno'], 'verbose_name': 'Dichiarazione di Intento', 'verbose_name_plural': 'Dichiarazioni di Intento'},
        ),
    ]
