# Generated by Django 5.1.7 on 2025-03-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornitore',
            options={'ordering': ['ragione_sociale']},
        ),
        migrations.AddField(
            model_name='fornitore',
            name='cap',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fornitore',
            name='citta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fornitore',
            name='paese',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fornitore',
            name='provincia',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
