# Generated by Django 5.1.7 on 2025-03-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0002_alter_fornitore_options_fornitore_cap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dogana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['descrizione'],
            },
        ),
        migrations.AlterField(
            model_name='fornitore',
            name='citta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Città'),
        ),
    ]
