# Generated by Django 4.2.20 on 2025-04-14 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0003_dogana_azienda_fornitore_azienda'),
        ('documenti', '0007_alter_dichiarazioneintento_plafond_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Durc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_durc', models.CharField(max_length=100)),
                ('data_durc', models.DateField()),
                ('scadenza_durc', models.DateField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='durc/')),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durc', to='anagrafiche.fornitore')),
            ],
            options={
                'ordering': ['-scadenza_durc'],
            },
        ),
    ]
