# Generated by Django 4.2.20 on 2025-04-14 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_azienda_comune_nascita_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documenti', '0009_alter_durc_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='durc',
            name='azienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.azienda'),
        ),
        migrations.AddField(
            model_name='durc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='durc',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
