# Generated by Django 4.2.20 on 2025-05-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documenti', '0010_durc_azienda_durc_created_at_durc_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dichiarazioneintento',
            name='numero_dichiarazione',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
